### ISSUE TITLE
Ошибка при работе с методом tasks.task.list

### ISSUE THREAD

**Issue by jounts** [leshchenko1979/fast_bitrix24#132]
```
bx = bt(webhook)

filter = {'RESPONSIBLE_ID': 6}
select = ['ID', 'TITLE', 'RESPONSIBLE_ID']
param =  {'filter': filter, 'select': select}
result = bx.get_all('tasks.task.list', params=param)

```
Возвращает ошибку:
  File "C:\.......\bt24\env\lib\site-packages\fast_bitrix24\user_request.py", line 147, in make_remaining_requests
    self.results.extend(remaining_results)
AttributeError: 'dict' object has no attribute 'extend'

fast-bitrix24==1.3.3

**Comment by leshchenko1979** [comment]
Проблема происходит из-за того, что `tasks.task.list` возвращает в поле `results` не список, а dict: `'tasks': [задача1, задача2, ...]`.
