### ISSUE TITLE
Инициализация http-клиента на стороне пользователя 

### ISSUE THREAD

**Issue by TRoll-94** [leshchenko1979/fast_bitrix24#146]
* Возникает ошибка при использовании библиотеки из **Windows 10** + **Python 3.9** + **fast_btirix==1.4.1**

> `aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host *url*:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')]`

P.S. Сертификат еще нет протух.

* Немного погуглив, понял, что у AIOHTTP проблемы с декодированием определенных сертификатов, и фиксится это передав в настройки AIOHTTP  параметр `verify_ssl=False`.

* Но сейчас, насколько я понял, нет возможности передать какие-то настройки, не влезая в исходники.

**Comment by leshchenko1979** [comment]
Предлагаемое решение:

В конструктор `Bitrix` / `BitrixAsync` добавить параметр `client`. В него пользователь будет передавать уже инициализированный экземпляр асинхронного http-клиента (`aiohttp` / `httpx` / какие еще?). Либа будет сама определять, какой клиент ей передан и автоматически использовать правильный интерфейс вызова метода `post` у этого клиента.
Пользователь будет сам отвечать за закрытие этого клиента. Если клиент не указан, то инициализация и закрытие клиента - ответственность либы.

Минусы / вопросы:

- Нужно будет следить за изменениями интерфейсов у всех поддерживаемых клиентов (что в принципе происходит очень редко)
- Пользователи могут забывать закрывать клиента (сами виноваты, надо пользоваться клиентом по умолчанию :) )
- Что будет, если пользователь в клиенте установит свои таймауты, и они будут конфликтовать с настройками, устанавливаемыми либой?
- Можно ли сделать так, чтобы, распознавая, какой клиент был передан, не импортировать все библиотеки, известные либе (чтобы экономить память / время инициализации)?

**Comment by leshchenko1979** [comment]
@TRoll-94 

А че-то не могу найти этого:
> Немного погуглив, понял, что у AIOHTTP проблемы с декодированием определенных сертификатов, и фиксится это передав в настройки AIOHTTP параметр verify_ssl=False.

Можно ссылку, плз?

**Comment by leshchenko1979** [comment]
В ветке `client-provided-by-user` залита новая версия.

Для тестирования нужно сделать:
```
git clone https://github.com/leshchenko1979/fast_bitrix24
cd fast_bitrix24
checkout client-provided-by-user
pip install -e .
```

После этого нужно в вашем коде сделать:
```
client = aiohttp.ClientSession(<ваши параметры клиента>)
bx = Bitrix(webhook, client=client)
<Тут вызовы Битрикс>
```
