### ISSUE TITLE
Не могу задать null свойству объекта при вызове bitrix.call('...', {})

### ISSUE THREAD

**Issue by DAVIDhaker** [leshchenko1979/fast_bitrix24#156]
![Screenshot_20220407_072957](https://user-images.githubusercontent.com/23550085/162120467-633558de-98de-41c0-b0c5-4d770661c27d.png)
![Screenshot_20220407_073015](https://user-images.githubusercontent.com/23550085/162120469-6086855b-f5f4-44b5-93c5-481de2b5f80a.png)
Есть товар. При обновлении у него описания я не могу его очистить. Делаю так:

```python
bitrix = Bitrix('http://hook path')
bitrix.call('crm.product.update', {
    "id": 123,
    "fields": {
        "DESCRIPTION": None
    }
})
```

в итоге в описание товара красуется None. Пробовал с False, пустой строкой - не проходит. Задача - привести значение поля сущности к реальному "null".

**Comment by DAVIDhaker** [comment]
Нет, дело не в API. Библиотека None преобразует в строку "None" и отправляет это БТС.

PS: Спасибо за вклад в opensource.

**Comment by leshchenko1979** [comment]
Да, нашел причину.

При формировании батча, отправляемого в Битрикс, все элементы `itemlist`, приходящие в `call` (равно как и в любые другие типы запросов), сериализуются в url, который содержит данные элемента. При этом элементы, содержащие None, заворачиваются в токен типа `...&param=None&...`, что Битриксом интерпретируется как строка `"None"`.

Варианты решения:
1. Для запросов call с одним элементов не производить формирование батча, а класть этот единый элемент в json и передавать так в Битрикс. Не нравится, потому что тогда невозможно будет формировать батчи при вызове с несколькими элементами, содержащими None. Каждый запрос с None придется отправлять отдельно.
2. Попробовать вместо `"None"` при сериализации данных элемента использовать `"null"`. @DAVIDhaker - вы не пробовали отправлять команду с `"DESCRIPTION=null"` через url?

**Comment by leshchenko1979** [comment]
В #158 к методу `call()` был добавлен параметр `raw`. Если его установить в `True`, то ваша задача, кажется, будет решена.

Сможете сделать форк, чекаутнуть ветку `raw-call` и проверить, что при вызове 
```
bitrix = Bitrix('http://hook path')
param = {
    "id": 123,
    "fields": {
        "DESCRIPTION": None
    }
}
bitrix.call('crm.product.update', param, raw=True)
```
описание продукта стирается?

**Comment by leshchenko1979** [comment]
А можно вас попросить уточнить, как вы сделали такой вывод?

**Comment by DAVIDhaker** [comment]
Wireshark-ом глянул.19:53, 26 May 2022, Alexey Leshchenko ***@***.***>:
А можно вас попросить уточнить, как вы сделали такой вывод?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile
