### ISSUE TITLE
Ошибка при использовании get_all для метода crm.lead.fields

### ISSUE THREAD

**Issue by zertyuiop** [leshchenko1979/fast_bitrix24#161]
leads_fields = await bx24.get_all('crm.lead.fields')

ViolationError: File C:\ProgramData\mambaforge\lib\site-packages\fast_bitrix24\user_request.py, line 135 in GetAllUserRequest:
isinstance(self.results, list):
isinstance(self.results, list) was False
result was None
self was <fast_bitrix24.user_request.GetAllUserRequest object at 0x000002B1D81AAA90>

**Comment by leshchenko1979** [comment]
Проблема решена последним релизом: https://github.com/leshchenko1979/fast_bitrix24/releases/tag/1.5.4
