### ISSUE TITLE
Как получить голый ответ от битрикса, а не список

### ISSUE THREAD

**Issue by MVKozlov** [leshchenko1979/fast_bitrix24#171]
Хотел получить количество объектов.
Как я понял, в битриксе нет чего-нибудь типа crm.contact.count

попытался использовать call("crm.contact.list"), но в ответ сразу список, никаких count, total, next, time, даже с использованием raw=True

Есть такая возможность ? или просто дёргать хук напрямую ?

**Comment by leshchenko1979** [comment]
Дергать хук напрямую. Либо наследоваться от `fast_bitrix24.user_requests.CallUserRequest` и менять метод `run()`.

**Comment by leshchenko1979** [comment]
Хук напрямую и смотреть results.total

С уважением,
Алексей Лещенко
+7 985 222 79 49

________________________________
От: Max Kozlov ***@***.***>
Отправлено: Friday, May 27, 2022 4:23:46 PM
Кому: leshchenko1979/fast_bitrix24 ***@***.***>
Копия: Subscribed ***@***.***>
Тема: [leshchenko1979/fast_bitrix24] Как получить голый ответ от битрикса, а не список (Issue #171)


Хотел получить количество объектов.
Как я понял, в битриксе нет чего-нибудь типа crm.contact.count

попытался использовать call("crm.contact.list"), но в ответ сразу список, никаких count, total, next, time, даже с использованием raw=True

Есть такая возможность ? или просто дёргать хук напрямую ?
