### ISSUE TITLE
Несовпадение аннотации типов с документацией в методе get_by_ID

### ISSUE THREAD

**Issue by andrpocc** [leshchenko1979/fast_bitrix24#188]
Фактически, как я понял, метод возвращает словарь с ключами ID и значениями ответа от bx24 по каждому ID. Но в аннотации типов указан тип list. 

```
@log
    async def get_by_ID(
        self,
        method: str,
        ID_list: Iterable,
        ID_field_name: str = "ID",
        params: dict = None,
    ) -> list:
```

#### Из документации
Метод [get_by_ID()](https://github.com/leshchenko1979/fast_bitrix24/blob/master/API.md#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-getbyidself-method-str-idlist-iterable-idfieldname-str--id-params-dict--none---dict) возвращает словарь с элементами вида ID: result, где result - ответ сервера относительно этого ID.

**Comment by leshchenko1979** [comment]
Согласен. Сможете сделать PR?
