### ISSUE TITLE
Ошибка при выгрузке ~70000 сделок методом get_all

### ISSUE THREAD

**Issue by asizhuk** [leshchenko1979/fast_bitrix24#192]
Добрый день. 3 минуты поработал и выдал ошибку. Из-за чего это? Получаю 69 000 сделок. 
Но если получать небольшое кол-во (5000), то все нормально
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/40548204/179310220-6850082a-0902-44f1-96de-55dc5c2f81d5.png">
<img width="513" alt="image" src="https://user-images.githubusercontent.com/40548204/179310284-cf12d87a-69db-4cad-8180-84b2329ab9fa.png">

**Comment by leshchenko1979** [comment]
Дубль #187
