### ISSUE TITLE
Problem with get_all and crm.type.list (and maybe other calls)

### ISSUE THREAD

**Issue by akvalibra** [leshchenko1979/fast_bitrix24#196]
When I call b.get_all('crm.type.list') Bitrix24 return a error:

{"error":100,"error_description":"Unknown field definition `I_D` (I_D) for \\Bitrix\\Crm\\Model\\Dynamic\\Type Entity."}

I have debug and found that fast_bitrix24 automatically add {"order": {"ID": "ASC"}} in Post Body
But if I made a call in Postman and put ID with small letters call is OK

>> {"order": {"id": "ASC"}}

**Comment by leshchenko1979** [comment]
Используйте b.call("crm.type.list")

С уважением,
Алексей Лещенко
+7 985 222 79 49

________________________________
От: Sasha ***@***.***>
Отправлено: Wednesday, August 17, 2022 4:53:51 PM
Кому: leshchenko1979/fast_bitrix24 ***@***.***>
Копия: Subscribed ***@***.***>
Тема: [leshchenko1979/fast_bitrix24] Problem with get_all and crm.type.list (and maybe other calls) (Issue #196)


When I call b.get_all('crm.type.list') Bitrix24 return a error:

{"error":100,"error_description":"Unknown field definition I_D (I_D) for \Bitrix\Crm\Model\Dynamic\Type Entity."}

I have debug and found that fast_bitrix24 automatically add {"order": {"ID": "ASC"}} in Post Body
But if I made a call in Postman and put ID with small letters call is OK

{"order": {"id": "ASC"}}

**Comment by akvalibra** [comment]
Привет

b.call('crm.type.list',raw=True)  е во ред

Поздрав
Сашо Кузманов
МКД
