### ISSUE TITLE
проблема с методом - task.elapseditem.getlist

### ISSUE THREAD

**Issue by DenisDenvic** [leshchenko1979/fast_bitrix24#197]
1. обработать метод task.elapseditem.getlist через get_all() невозможно - дает 400 ошибку. Это если передвать параметры
2. Если параметры не отдавать, то метод отдает только первые 50 записей
и в этом случае выводит еррор: \user_request.py:168: RuntimeWarning: Number of results returned (50) doesn't equal 'total' from the server reply (23732) 

Предполагаю, что get_all() ожилает в методе .listб но получение трудозатрат у Битрикса особенное и  использует .getlist

**Comment by leshchenko1979** [comment]
Смотрите #157
