### ISSUE TITLE
Как получить из Битрикса полный список через list_and_get()

### ISSUE THREAD

**Issue by krinichniy** [leshchenko1979/fast_bitrix24#206]
Выполняю следующий код:

from fast_bitrix24 import Bitrix
import pandas as pd
import numpy as np
b = Bitrix('вебхук')
deals = b.list_and_get('crm.deal')
deals = pd.DataFrame(deals)
print (deals)
и получаю такую ошибку: "C:\Users\ххх\Python\Python310\lib\site-packages\fast_bitrix24\user_request.py:168: RuntimeWarning: Number of results returned (50) doesn't equal 'total' from the server reply (753128) warnings.warn( 0%| | 0/50 [00:00<?, ?it/s]"

При выводе значений получаю пустой датафрейм.

При этом выполняю такой код:

from fast_bitrix24 import Bitrix
import pandas as pd
import numpy as np
b = Bitrix('вебхук')
deals = b.list_and_get('crm.deal')
deals = pd.DataFrame(deals)
print (deals)
И получаю датафрейм из 50 записей.

Подскажите, что не так делаю? Как получить полный список записей?

**Comment by leshchenko1979** [comment]
На правильный метод REST API. Вам нужен не `crm.deal`, а `crm.deal.list`.

**Comment by krinichniy** [comment]
Извиняюсь, в строчке
"deals = b.list_and_get('crm.deal')"
ошибся, когда переносил.
В тестах у меня "deals = b.get_all('crm.deal.list')".

А что может быть не так в этой части?

"Выполняю следующий код:
from fast_bitrix24 import Bitrix
import pandas as pd
import numpy as np
b = Bitrix('вебхук')
deals = b.list_and_get('crm.deal')
deals = pd.DataFrame(deals)
print (deals)
и получаю такую ошибку: "C:\Users\ххх\Python\Python310\lib\site-packages\fast_bitrix24\user_request.py:168: RuntimeWarning: Number of results returned (50) doesn't equal 'total' from the server reply (753128) warnings.warn( 0%| | 0/50 [00:00<?, ?it/s]"

При выводе значений получаю пустой датафрейм."

Если добавляю в list_and_get crm.deal.list, то ошибка:
<pi>icontract.errors.ViolationError: File C:\USERS\ILMAW\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\lib\site-packages\fast_bitrix24\user_request.py, line 291 in ListAndGetUserRequest:
list_and_get(): "method_branch" should not end in ".list" or ".get": not re.search

**Comment by krinichniy** [comment]
> Неправильный метод REST API. Вам нужен не `crm.deal`, а `crm.deal.list`.

Извиняюсь, в строчке
"deals = b.list_and_get('crm.deal')"
ошибся, когда переносил.
В тестах у меня "deals = b.get_all('crm.deal.list')".

А что может быть не так в этой части?

"Выполняю следующий код:
from fast_bitrix24 import Bitrix
import pandas as pd
import numpy as np
b = Bitrix('вебхук')
deals = b.list_and_get('crm.deal')
deals = pd.DataFrame(deals)
print (deals)
и получаю такую ошибку: "C:\Users\ххх\Python\Python310\lib\site-packages\fast_bitrix24\user_request.py:168: RuntimeWarning: Number of results returned (50) doesn't equal 'total' from the server reply (753128) warnings.warn( 0%| | 0/50 [00:00<?, ?it/s]"

При выводе значений получаю пустой датафрейм."

Если добавляю в list_and_get crm.deal.list, то ошибка:
icontract.errors.ViolationError: File C:\USERS\ILMAW\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\lib\site-packages\fast_bitrix24\user_request.py, line 291 in ListAndGetUserRequest:
list_and_get(): "method_branch" should not end in ".list" or ".get": not re.search

**Comment by leshchenko1979** [comment]
А можете приложить логи, плз?

**Comment by krinichniy** [comment]
> А можете приложить логи, плз?
Направил лог и комментарий на почту

**Comment by leshchenko1979** [comment]
Вроде разобрались, что источник проблемы в устаревшей коробочной версии Битрикс.
