### ISSUE TITLE
Проблема с обработкой вызовов в синхронном режиме в Spyder (IPython)

### ISSUE THREAD

**Issue by Vasilexu** [leshchenko1979/fast_bitrix24#212]
Пытаюсь выполнить код из readme
```python
b = Bitrix(FAST_BITRIX24_TEST_WEBHOOK)
deals = b.get_all('crm.deal.list')
contacts = b.get_by_ID(
    'crm.deal.contact.items.get',
    [d['ID'] for d in deals])
``` 

Получаю ошибку

![image](https://github.com/leshchenko1979/fast_bitrix24/assets/106771491/d32feb18-14ef-4d88-b563-286c91e30108)

Как получить из запроса данные в синхронном режиме?

**Comment by leshchenko1979** [comment]
fast_bitrix24 использует под капотом асинхронный код. Синхронный интерфейс
библиотеки — всего лишь обёртка над асинхронным кодом.

Есть какое-то подтверждение, что spyder умеет выполнять асинхронный код?


вт, 25 июл. 2023 г., 17:26 Vasilexu ***@***.***>:

**Comment by Vasilexu** [comment]
При попытке выполнения кода
```python
import asyncio

async def main():
    print('hello')
    await asyncio.sleep(1)
    print('world')

asyncio.run(main())
```
получаю ошибку
![image](https://github.com/leshchenko1979/fast_bitrix24/assets/106771491/ba584ef4-d78e-4602-9e60-9053110901e1)

На stackoverflow разобрана подобная ошибка (см. https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop-when-using-jupyter-no).

Сниппет из разбора решил проблему на тестовом коде
```python
try:
    loop = asyncio.get_running_loop()
except RuntimeError:  # 'RuntimeError: There is no current event loop...'
    loop = None

if loop and loop.is_running():
    print('Async event loop already running. Adding coroutine to the event loop.')
    tsk = loop.create_task(main())
    # ^-- https://docs.python.org/3/library/asyncio-task.html#task-object
    # Optionally, a callback function can be executed when the coroutine completes
    tsk.add_done_callback(
        lambda t: print(f'Task done with result={t.result()}  << return val of main()'))
else:
    print('Starting new event loop')
    result = asyncio.run(main())
``` 
Но при попытке вызвать первоначальный код из readme через сниппет
```python
async def main():
    b = Bitrix(FAST_BITRIX24_TEST_WEBHOOK)
    deals = b.get_all('crm.deal.list')
    contacts = b.get_by_ID(
        'crm.deal.contact.items.get',
        [d['ID'] for d in deals])
#далее main() вызывается сниппетом выше
``` 
получаю ошибку
![image](https://github.com/leshchenko1979/fast_bitrix24/assets/106771491/f2c97ee3-c89f-42f2-b642-afd28645ba5b)

Верно ли я понимаю, что проблема связана с исполнением файла через IPython?
Т.е. в любой другой IDE или с другим интерпретатором вопрос должен закрыться?

**Comment by Vasilexu** [comment]
Сменил IDE, чтобы не работать в окружении Anconda. В новом окружении проблем никаких нет.
