### ISSUE TITLE
Ошибка при вызове метода task.commentitem.getlist

### ISSUE THREAD

**Issue by rasperepodvipodvert** [leshchenko1979/fast_bitrix24#214]
Ошибка при вызове метода `task.commentitem.getlist`

```
2024-01-29 22:06:31,526 - fast_bitrix24 - INFO - Slow mode enabled: {'max_concurrent_requests': 1}
Starting get_all((<fast_bitrix24.bitrix.Bitrix object at 0x7f50eddcf010>, 'task.commentitem.getlist', {'TASKID': '5540'}), {})
2024-01-29 22:06:31,526 - fast_bitrix24 - INFO - Starting get_all((<fast_bitrix24.bitrix.Bitrix object at 0x7f50eddcf010>, 'task.commentitem.getlist', {'TASKID': '5540'}), {})
Concurrent requests increased: {'mcr_cur_limit': 1}
2024-01-29 22:06:31,526 - fast_bitrix24 - DEBUG - Concurrent requests increased: {'mcr_cur_limit': 1}
Requesting {'method': task.commentitem.getlist, 'params': {'TASKID': '5540', 'order': {'ID': 'ASC'}}}
2024-01-29 22:06:31,527 - fast_bitrix24 - DEBUG - Requesting {'method': task.commentitem.getlist, 'params': {'TASKID': '5540', 'order': {'ID': 'ASC'}}}
2024-01-29 22:06:31,575 - root - ERROR - 400, message='Bad Request', url=URL('WEBHOOKURL/task.commentitem.getlist')
```

Вызываю так:

```python
self.b24.get_all(
'task.commentitem.getlist',
  {
    'TASKID': task_id,
  },
)
```

**Comment by rasperepodvipodvert** [comment]
Судя по всему у меня нет доступа к задачам, у которых я запрашиваю коменты.

вот эта конструкция, почему-то отдает не те задачи:

```
tasks = self.b24.get_all(
                'tasks.task.list',
                {
                    'filter': {
                        'GROUP_ID': group_id,
                        'RESPONSIBLE_ID': ["1", "2", "3"],
                        'REAL_STATUS': ["1", "2", "3"]
                    }
                }
            )
```

**Comment by leshchenko1979** [comment]
Если у вас возникла проблема:

0. Убедитесь, что проблема именно в либе fast_bitrix24. Если не в ней, то вам, возможно, будет эффективней попросить помощи не в этом чате, а в другом месте.

1. Напишите код, который вы выполняете.

2. Укажите, в какой среде выполняете (ключевое — в ноутбуках или нет).

3. Приложите ссылку на документацию по используемому вами методу REST API Битрикс24.

4. Напишите результат, который вы получаете. 

Если код выполняется с ошибкой, приведите ПОЛНОСТЬЮ трейсинг ошибки. 

Если код отрабатывает без ошибок, но вы недовольны результатом, то не забудьте указать, какой результат вы ожидаете. 

5. Приложите файл с ПОЛНЫМИ логами, которые генерирует ваш скрипт.

Чтобы получить логи, нужно добавить в начало вашего скрипта:

```
import logging

logging.getLogger('fast_bitrix24').addHandler(logging.StreamHandler())
```

**Comment by rasperepodvipodvert** [comment]
Проблема выявлена в сервере битрикса, не в библиотеке. Опубликованный через nginx сервер возвращал не верные ответы.
