### ISSUE TITLE
как получить текстовое значение списка пользовательского поля сделки

### ISSUE THREAD

**Issue by NudelMark** [leshchenko1979/fast_bitrix24#215]
Здравствуйте, помогите пожалуйста, указываю в коде что хочу получить пользовательское поле в сделке типа список, указываю какое поле хочу выгрузить и получаю вместо слов цифры, как мне получить слова которые я выбрал в сделке

**Comment by NudelMark** [comment]
Вот мой код:
import json
from fast_bitrix24 import Bitrix

# Инициализация клиента Bitrix24
web_hook_url = ''  # Замените на ваш веб-хук URL
b = Bitrix(web_hook_url)
# Код пользовательского поля, которое нужно выгрузить
custom_field_code = 'UF_CRM_1685366887323'

# Получение списка всех сделок с конкретным пользовательским полем
deals = b.get_all('crm.deal.list', params={'select': ['ID', 'TYPE_ID', custom_field_code]})

# Создание списка с информацией о сделках и значением пользовательского поля
deals_with_custom_field = [
    {
        'ID': deal['ID'],
        'Тип сделки': deal['TYPE_ID'],
        "Условия оплаты": deal.get(custom_field_code)
    }
    for deal in deals
]

# Сохранение информации в JSON файл
with open('deals_with_specific_custom_field.json', 'w', encoding='utf-8') as json_file:
    json.dump(deals_with_custom_field, json_file, ensure_ascii=False, indent=4)

print(f"Сделки с пользовательским полем '{custom_field_code}' сохранены в файл 'deals_with_specific_custom_field.json'")

**Comment by leshchenko1979** [comment]
Вот как нужно делать багрепорт: https://t.me/c/1404592045/4445

Пока что закрываю, если ещё актуально, то добавьте требуемую инфо и откройте заново.

**Comment by NudelMark** [comment]
я не могу посмотреть сообщение так как я не участник чата

**Comment by NudelMark** [comment]
уже смог открыть
