### ISSUE TITLE
Сумма времени всех запросов к методу превышает 480 секунд в рамках прошедших 10 минут / Обход ошибки

### ISSUE THREAD

**Issue by lacoste-sochi** [leshchenko1979/fast_bitrix24#216]
У Битрикс24 есть лимиты

Хорошо расписаны тут
https://inexsu.wordpress.com/2022/05/30/битрикс24-rest-ограничения-запросов/

На данный момент у меня более 300к элементов, которые превышают 480 секунд (8 минут), по истечению

`  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://81.163.21.198/rest/54/**************/batch')`

Я так понимаю ошибка не обрабатывается...

Выход есть, если выбивает ошибка касаемо лимита этого,можно в sleep кинуть, на данный момент у меня не получается таким способом
`
            # Переменная для отслеживания успешности запроса
            success = False
            # Переменная для хранения полученных данных
            bitrix_items[field] = []

            while not success:
                try:
                    # Производим вызовы
                    items = await b.get_all(
                        method=methods[field],
                        params={
                            'select': list(item.keys()),
                            **params,  # Добавляем дополнительные параметры
                            'filter': filters[field]
                        }
                    )
                    bitrix_items[field].extend(items)  # Добавляем полученные элементы
                    success = True  # Успешный запрос, выходим из цикла
                except aiohttp.client_exceptions.ContentTypeError as e:
                    print(f"Ошибка при запросе к Bitrix24: {e}")
                    print("Повторный запрос через 5 минут...")
                    await asyncio.sleep(300)  # Ожидание 5 минут перед повторным запросом

Причина, скрипт ожидает полные данные, а не берет порциями ((( ..Я думаю если будет генератор, то проблема будет решена

**Comment by leshchenko1979** [comment]
Внутри либы уже есть цикл повторных попыток при получении ошибок.

Я не очень понимаю, как применение генератора может решить эту проблему.

На мой взгляд, надо решать именно проблему с установкой правильных таймаутов в уже существующем коде библиотеки.

**Comment by leshchenko1979** [comment]
Дублирует #187
