### ISSUE TITLE
Warning, если get_all используется с методом, не кончающимся на *.list

### ISSUE THREAD

**Issue by leshchenko1979** [leshchenko1979/fast_bitrix24#224]

**Comment by exec-to** [comment]
Алексей, добрый день!
Можно ли отключить это предупреждение?

> UserWarning: get_all() should be used only with methods that end with '.list' or '.getlist'. You are using '{self.st_method}'. Use get_by_ID() or call() instead.

Оно не применимо для универсальных списков, т.к. вызов API для списка элементов называется иначе: [lists.element.get](https://dev.1c-bitrix.ru/rest_help/lists/elements/lists_element_get.php)

**Comment by leshchenko1979** [comment]
В версии 1.7.1 как раз сделана эта поправка
