### ISSUE TITLE
Добавить возможность работать с fast_bitrix24 из приложения используя access_token вместо хука

### ISSUE THREAD

**Issue by MSITETOP** [leshchenko1979/fast_bitrix24#242]
Добрый день!
Планируем попробовать использовать ваше решение в нашихх приложениях для Б24. В целом это у нас успешно получилось с незначительными доработками вашего решения.

Пример использования
```
from fast_bitrix24 import Bitrix

# вместо хука указываем endpoint
webhook = "https://your_domain.bitrix24.ru/rest/"

# в параметре auth указываем токен полученный приложением access_token
auth = "f88f976600.................................6db4fcd154f24"
bx = Bitrix(webhook, auth)
```

а дальше все как обычно. Единственное появляется необходимость рефрешить этот токен, но это у нас происходит за пределами fast_bitrix24

позволяет не привязываться к конкретной безе хранения токенов доступа

**Comment by MSITETOP** [comment]
отправил PR . 
возможно это можно будет использовать?

**Comment by leshchenko1979** [comment]
Дублирует #243
