### ISSUE TITLE
Авторизация по OAuth

### ISSUE THREAD

**Issue by leshchenko1979** [leshchenko1979/fast_bitrix24#40]

**Comment by leshchenko1979** [comment]
- [ ] Найти раздел доки про авторизацию по OAuth
- [ ] Сделать тестовый аккаунт, где будет требоваться авторизация по OAuth

**Comment by leshchenko1979** [comment]
Можно взять за основу то, как сделано в https://github.com/yarbshk/pybitrix24

**Comment by leshchenko1979** [comment]
Можно сделать так:

В конструктор Bitrix() можно будет передать функцию-генератор, которая будет yield-ить токены. 

Обращение к этой функции будет происходить каждый раз, когда от сервера будет приходить сообщение "Нужен токен" или "Токен истек".

**Comment by leshchenko1979** [comment]
> Можно сделать так:
> 
> В конструктор Bitrix() можно будет передать функцию-генератор, которая будет yield-ить токены.
> 
> Обращение к этой функции будет происходить каждый раз, когда от сервера будет приходить ошибка 403.

Нет, слишком сложно. Нужен не генератор, а обычная функция. (Генератор нужен, когда внутри функции нужно сохранять состояние.)

**Comment by leshchenko1979** [comment]
Возможно, имеет смысл в конструктор `Bitrix()` добавить параметр `auth_func`. 

Эта функция, если она указана, будет вызываться перед первым запросом или когда сервер вернул ошибку `401`. Если функция вернёт строку, то добавляем её как параметр `auth` в URL запроса. Если словарь, то считаем, что в словаре заголовки, которые нужно добавить к запросу.

Если вместо функции указана константа, то используем константу, как описано выше.

Заодно решит #140.

**Comment by leshchenko1979** [comment]
Тут подсказывают, что нужно взять реализацию отсюда: https://github.com/momoru-kun/PyBitrix/blob/main/pybitrix/pybitrix.py

**Comment by notrurs** [comment]
Добрый день! По итогу возможность авторизации по OAuth ещё не добавили? Есть ли планы по этой фиче?

**Comment by leshchenko1979** [comment]
> @leshchenko1979 Добрый день! По итогу возможность авторизации по OAuth ещё не добавили? Есть ли планы по этой фиче?

В #149 лежит веточка, которая ждёт тестирования. Если там все работает ОК, то можно выкатывать в мейн.

Не желаете ли протестировать?

**Comment by notrurs** [comment]
@leshchenko1979 на днях тестану, отпишусь)

**Comment by leshchenko1979** [comment]
Реализовано в #243
