### ISSUE TITLE
Неправильная передача списочных параметров

### ISSUE THREAD

**Issue by skvortsovse** [leshchenko1979/fast_bitrix24#54]
Например, при передаче
`"PHONE": [ { "VALUE": "+79613152783", "VALUE_TYPE": "MOBILE" } ]`
создается контакт с телефоном типа Рабочий (по умолчанию)
Проверил такой же через postman, там корректно создается.

**Comment by leshchenko1979** [comment]
Так в итоге какое имя поля - `PHONE` или `PHONES`? :) Может, дело в названии поля?

**Comment by skvortsovse** [comment]
Да, именно PHONE, как в документации.
Все прикрепил)
Через постман:
<img width="642" alt="Screenshot 2020-09-11 at 10 33 30" src="https://user-images.githubusercontent.com/4902035/92884314-663fb680-f41a-11ea-841c-6db65254ba39.png">
<img width="693" alt="Screenshot 2020-09-11 at 10 32 27" src="https://user-images.githubusercontent.com/4902035/92884326-693aa700-f41a-11ea-8252-1f6f1baadf25.png">
Через API:
<img width="748" alt="Screenshot 2020-09-11 at 10 42 25" src="https://user-images.githubusercontent.com/4902035/92885754-bff4b080-f41b-11ea-9c7d-61b0f5fbbc67.png">
<img width="916" alt="Screenshot 2020-09-11 at 10 41 11" src="https://user-images.githubusercontent.com/4902035/92885770-c2570a80-f41b-11ea-85d8-7c59af676c84.png">

`    def export_clients_test(self):

        while True:

            clients = Client.objects.filter(bitrix_id__isnull=True, lead__operator_primary__isnull=False)[:2]

            clients = list(clients)
            if not clients:
                break

            clients_data = list()

            for client in clients:

                phones = list()
                for c2c in ContactToClient.objects.filter(client=client):
                    # value_type = "MOBILE" if c2c.type == ContactToClient.PRIMARY else "OTHER"

                    phones.append({
                        "VALUE": '+' + c2c.contact.phone,
                        "VALUE_TYPE": "MOBILE"
                    })

                fields = {
                    'NAME': client.name,
                    'OPENED': "Y",
                    'EXPORT': "N",
                    'ORIGINATOR_ID': 'PLATFORM',
                    'ORIGIN_ID': client.id,
                    "ASSIGNED_BY_ID": 1,
                    "TYPE_ID": "CLIENT",
                    "PHONE": phones,
                }
                
                data = dict(
                    fields=fields,
                )

                clients_data.append(data)


            slower_speed = 1.2
            with slow(slower_speed):
                result = self.bitrix.call('crm.contact.add', clients_data)

                for client in clients:
                    client.bitrix_id = result.pop(0)
                    client.save()

                print(result)

            break`

**Comment by leshchenko1979** [comment]
Да, повторил ошибку у себя, спасибо, @skvortsovse!

Похоже, проблема в том, как я сериализую вложенные списки параметров. Я вижу, что вы в Postman вставляете параметры в тело запроса (я не знал, что так работает 😄 ) , а я пытаюсь их запихнуть в сам URI, да при том еще так, чтобы Битрикс24 правильно их прочитал (там есть особенность, что он любит, когда списки ему подаются не в виде `...&list[0]=abc&list[1]=def&...`, а с опусканием индекса = `...&list[]=abc&list[]=def&...`). Возможно, где-то там, на втором+ уровне сложности, возникают баги и начинает теряться информация.

Я попробую передавать параметры через тело - возможно, в этом вся загвоздка.

**Comment by skvortsovse** [comment]
А сам запрос на добавление объекта методом POST происходит? Или GET?
Если Битрикс разрешает методом GET с данными в url изменять объекты на сервере, то это слишком) 

Вообще, у вас классная библиотека. Как раз сейчас задача переехать на Битрикс, и нужно загрузить сотни тысяч объектов из нашей системы.

**Comment by leshchenko1979** [comment]
Да, Битрикс пишет, что можно и `POST`, и `GET`. 😀 Я использую `GET`. 😀

И спасибо за комплимент! Будет интересно, какие у вас максимальные скорости обмена с сервером получатся.

**Comment by leshchenko1979** [comment]
@skvortsovse - что-то у меня не получается передавать параметры в теле запроса. Пробую простое:

![image](https://user-images.githubusercontent.com/60138889/93324961-4562d100-f81f-11ea-875a-b4698fd7088f.png)

Видно, что сервер не увидел, что я в `select` прошу от него только `ID`. Как вы заставляете его ходить в тело запроса за параметрами? Мои посмотреть ваши заголовки запроса? Вот мои:

![image](https://user-images.githubusercontent.com/60138889/93325174-8fe44d80-f81f-11ea-9ab2-f528a6fa64da.png)

**Comment by skvortsovse** [comment]
Это из-за того что используете GET 🙂

Использовать GET для запросов изменяющих данные, это примерно как писать имена переменных на русском языке.

**Comment by skvortsovse** [comment]
Пардон, с телефона не увидел. Это запрос получения списка 🤦‍♂️
С компа попробую воссоздать.

**Comment by skvortsovse** [comment]
В GET в тело запроса вроде нельзя вставлять данные. (Но это не точно)

**Comment by leshchenko1979** [comment]
> В GET в тело запроса вроде нельзя вставлять данные. (Но это не точно)

Я бы в случае с Битриксом не верил здравому смыслу и все проверял экспериментально. 😭 

Если у вас в том запросе в Postman, где у вас получилось создать лид, поставить в URL команду crm.deal.list, а в body вставить, напр., `{"select": ["ID"]}`, сработает?

**Comment by leshchenko1979** [comment]
Да, попробовал `GET` заменить на `POST`, все пошло, спасибо!

**Comment by leshchenko1979** [comment]
Докладываю.

Научился из Postman передавать параметры в теле, научился из своей либы передавать параметры в теле. Вся самодельная магия с тем, чтобы закодировать параметры запроса в URI, ушла. (Возможно, в результате даже получится снять текущее ограничение на размер батча, которое налагалось максимальной длиной URI в 5280 символов.)

Однако оригинальный баг, обсуждаемый тут, остался - из Postman получается создать мобильный номер телефона, из либы - нет.

Пока дальнейших идей нет. 😢

**Comment by skvortsovse** [comment]
> Если у вас в том запросе в Postman, где у вас получилось создать лид, поставить в URL команду crm.deal.list, а в body вставить, напр., `{"select": ["ID"]}`, сработает?

Да, сработало
<img width="785" alt="Screenshot 2020-09-16 at 14 41 14" src="https://user-images.githubusercontent.com/4902035/93332693-e30fcd80-f82a-11ea-85ef-cb5f4b9acdad.png">

**Comment by skvortsovse** [comment]
> Однако оригинальный баг, обсуждаемый тут, остался - из Postman получается создать мобильный номер телефона, из либы - нет.
> 
> Пока дальнейших идей нет.

А можно вытащить сам запрос прям перед отправкой в Битрикс? Потом его вставить в Постман и смотреть что будет

**Comment by leshchenko1979** [comment]
А, нет. Был неправ. 

Дело в том, что у меня все списки запросов для ускорения заворачиваются в батчи, а это подразумевает построение URI с закодированными в него параметрами запроса. И этот код для сериализации параметров запроса в URI все еще остался, и загвоздка, наверное, в нем. 

Копаем дальше.

**Comment by leshchenko1979** [comment]
Поиск правильного алгоритма кодирования параметров запроса в URI идет в ветке https://github.com/leshchenko1979/fast_bitrix24/tree/correct_urlencode.

**Comment by leshchenko1979** [comment]
```
tasks1 = [
        {'ID': 281,
            'rows':
             [
             
                {"PRODUCT_NAME": 'ssssdsd', "PRICE": 5555,  "QUANTITY": 2, "CURRENCY": 'USD'},
                {"PRODUCT_ID": 2809, "PRICE": 100,  "QUANTITY": 2 }
                
            ]}
]           

        
    
lest = b.call('crm.lead.productrows.set', tasks1)
```

Раскладывает на отдельные ячейки:

![image](https://user-images.githubusercontent.com/60138889/97881240-34204600-1d33-11eb-906b-963973b81899.jpeg)

**Comment by leshchenko1979** [comment]
Последняя проблема (` productrows`) не подвердилась.
