### ISSUE TITLE
IndexError в случае, если URL для обращения к методу batch слишком длинный даже для одного параметра

### ISSUE THREAD

**Issue by devsagul** [leshchenko1979/fast_bitrix24#59]
Трейсбек:

```
Traceback (most recent call last):
  File "issue.py", line 22, in <module>
    deals = bitrix_client.call('tasks.task.add', params)
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/bitrix.py", line 102, in call
    return self.srh.run(CallUserRequest(self.srh, method, [items]).run())[0]
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/srh.py", line 68, in run
    return asyncio.run(async_wrapper(coroutine))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/srh.py", line 61, in async_wrapper
    result = await coroutine
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/user_request.py", line 191, in run
    results = await super().run()
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/user_request.py", line 153, in run
    results = await MultipleServerRequestHandlerPreserveIDs(
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/mult_request.py", line 89, in run
    await super().run()
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/mult_request.py", line 21, in run
    self.prepare_batches()
  File "/home/devsagul/projects/task-creation-from-mail/.venv/lib/python3.8/site-packages/fast_bitrix24/mult_request.py", line 41, in prepare_batches
    URI_len_used = self.srh.URI_len_used('batch', batches[0])
IndexError: list index out of range
```

Код для воспроизведения:

```
import os
from fast_bitrix24 import Bitrix

base_url = os.getenv('BITRIX_URL')
user_id = os.getenv('BITRIX_USER')
token = os.getenv('BITRIX_TOKEN')
group_id = os.getenv('BITRIX_GROUP')

url = f'{base_url}/rest/{user_id}/{token}/'
bitrix_client = Bitrix(url)

with open('lorem.txt', 'r') as f:
    description = f.read()

params = {
    'fields': {
        'TITLE': 'Тестовая задача для воспроизведения бага',
        'DESCRIPTION': description,
        'GROUP_ID': group_id,
        'RESPONSIBLE_ID': user_id,
    },
}
deals = bitrix_client.call('tasks.task.add', params)
```

Переменные окружения BITRIX_URL, BITRIX_USER, BITRIX_TOKEN, BITRIX_GROUP должны быть установлены в соответствии с конфигурацией вашего Битрикс24. lorem.txt -- текстовый файл на 10К символов.

Коротко о проблеме:
При вычислении батчей метод [prepare_batches](https://github.com/leshchenko1979/fast_bitrix24/blob/master/fast_bitrix24/mult_request.py#L27) пытается рассчитать количество параметров, которое можно посылать с каждым запросом. Если один из параметров по длине превышает [BITRIX_URI_MAX_LEN](https://github.com/leshchenko1979/fast_bitrix24/blob/470d10d95a2a6085719da71b7d02bcf25f43353a/fast_bitrix24/srh.py#L12), то расчетное количество параметров в батче становится равным нулю, [генерируется пустой список с батчами](https://github.com/leshchenko1979/fast_bitrix24/blob/master/fast_bitrix24/mult_request.py#L31), после чего при [очередной попытке рассчитать размер батча](https://github.com/leshchenko1979/fast_bitrix24/blob/470d10d95a2a6085719da71b7d02bcf25f43353a/fast_bitrix24/mult_request.py#L41) вызов падает с IndexError при обращении к первому батчу

**Comment by devsagul** [comment]
Одно из решений -- все-таки отказаться от передачи параметров через URL в GET-запросах, передавать их в теле POST-запроса. Проблема: необходимо как-то понимать, какой запрос в API битрикса семантически GET, а какой -- POST или переложить ответственность за это на клиента, предоставив методы `get` и `post` вместо `call`.

**Comment by leshchenko1979** [comment]
Привет и спасибо!

1. Чтобы передавать параметры в теле, нужно ставить `POST`. При этом сам Битрикс пишет, что `POST` работает для всех методов REST API (включая те, которые работают только на чтение), и это подтверждается тестами.

2. У меня готова ветка, где параметры передаются через тело, выложу через полчаса.

3. К сожалению, у меня в алгоритме все запросы упаковываются в батчи. Это даёт 50-кратное ускорение, но именно из-за этого предлагаемое решение не сработает. 

Чтобы бороться с проблемой, указанной в тикете, этот функционал надо будет отключить. Заодно изменить функционал извлечения результатов запроса - для батчей и для обычных запросов сервер возвращает разный формат результатов.

**Comment by leshchenko1979** [comment]
2. Залил: https://github.com/leshchenko1979/fast_bitrix24/tree/params-in-body

**Comment by leshchenko1979** [comment]
Посыпаю голову пеплом, поспешил вот тут:
> К сожалению, у меня в алгоритме все запросы упаковываются в батчи. Это даёт 50-кратное ускорение, но именно из-за этого предлагаемое решение не сработает.

Чтобы бороться с проблемой, указанной в тикете, этот функционал надо будет отключить. Заодно изменить функционал извлечения результатов запроса - для батчей и для обычных запросов сервер возвращает разный формат результатов.

Передача параметров через тело, кажется, решила проблему: https://github.com/leshchenko1979/fast_bitrix24/pull/61
