### ISSUE TITLE
Как использовать символы типов фильтрации в FILTER? Ошибка KeyError

### ISSUE THREAD

**Issue by jobinfopy** [leshchenko1979/fast_bitrix24#71]
`lists = b.get_all('crm.deal.list', params={
    'FILTER': {
        '!STAGE_ID': 'C11:WON',
    }
})`
При попытке использовать символы типов фильтрации '!', '<', '>' и др. получается ошибка KeyError: '%21STAGE_ID'.
Символ перед полем кодируется например в %21 и в итоге KeyError. Как исправить или правильно записать данную конструкцию?

**Comment by leshchenko1979** [comment]
Привет! Похоже на баг. Чуть позже сегодня займусь.

**Comment by leshchenko1979** [comment]
А можно полную трассировку ошибки увидеть? @jobinfopy

**Comment by leshchenko1979** [comment]
И второй вопрос: пробовали вместо `!` писать `<>` или `!=`?

**Comment by leshchenko1979** [comment]
Удалось воспроизвести ошибку. Она возникает в недрах импортированного модуля `php`, используемого для закодирования вложенных массивов параметров в URI-строку. Поищем другие модули.

См. также #3, #5 и #56

**Comment by leshchenko1979** [comment]
Также у лида фильтровать надо по полю `STATUS_ID`, а не `STAGE_ID`.

**Comment by leshchenko1979** [comment]
Готово, все работает. Обновляйтесь.

**Comment by jobinfopy** [comment]
Спасибо за столь быструю реакцию))
Обнаружился ещё момент с выборкой пустых/непустых значений. Работа со списками. Фильтрует если передавать `False`. Но при этом получаем RuntimeWarning и только первые 50 значений. Хотя в прогресс-баре указывается общее правильное количество элементов подходящих под условия фильтра:
> 14%|█▍        | 50/355 [00:00<?, ?it/s]
\user_request.py:142: RuntimeWarning: Number of results returned (50) doesn't equal 'total' from the server reply (355)
  RuntimeWarning)

`lists = b.get_all('lists.element.get', params={
    'IBLOCK_TYPE_ID': 'lists',
    'IBLOCK_ID': '29',
    'FILTER': {
        '%PROPERTY_199': False,
    }
})`

**Comment by leshchenko1979** [comment]
Перенёс в #75. Посмотрю.
