### ISSUE TITLE
user.add

### ISSUE THREAD

**Issue by ricotioloco** [leshchenko1979/fast_bitrix24#85]
Используя метод call_batch() пользователи добавляются на портал по одному
```
from fast_bitrix24 import *

webhook = "https://latiendadeflores.bitrix24.ru/rest/1/<webhook>/"
b = Bitrix(webhook)
name = 'Test_user'
email = '@3.ru'
phone = 0
count = 2352
payload = {
     'halt': 0,
 }
 for i in range(50):
      payload['cmd']={}
 
     for k in range(50):
         payload['cmd']['add_user'+str(count)] = f'user.add?NAME={name+str(count)}&EMAIL={str(count)+email}&UF_DEPARTMENT=11&UF_PHONE_INNER={count}'
         count += 1
     result = b.call_batch(payload)
     print(result)
     del payload['cmd']
```
По окончании добавления первого полтинника пользователей вылетает exception
![2020-11-23_15-23](https://user-images.githubusercontent.com/71933392/99961719-f053b600-2d9f-11eb-87f6-93e4bb9fa835.png)

**Comment by leshchenko1979** [comment]
Судя по трассировке, проблема на стороне Битрикса (gateway timeout).

На прошлой неделе были массовые сбои в Битриксе - возможно, это отголоски.

Насколько давно проявляется проблема?

**Comment by ricotioloco** [comment]
Только сегодня установил модуль. Да, вполне возможно, что и Битрикс лагает, с ним это регулярно случается. Спасибо за оперативную реакцию)

**Comment by leshchenko1979** [comment]
Я бы рекомендовал для вашей задачи использовать `call('user.add', item_list)`, где `item_list` - список словарей с параметрами (`NAME`, `EMAIL` и т.д.).

Упаковка в батч автоматом, а у вас будет чище код.

**Comment by leshchenko1979** [comment]
@ricotioloco
Я предполагаю, все наладилось? 
Если нет, открывайте этот тикет заново, плз.

**Comment by ricotioloco** [comment]
К сожалению нет, не наладилось. Сегодня утром пытался еще раз запустить добавление пользователей, так же, добавляются по одному

**Comment by leshchenko1979** [comment]
ОК, я попробую у себя повторить.

**Comment by leshchenko1979** [comment]
Пишу тест:
``` python
    def test_batch_issue_85(self, get_test):

        b = get_test

        name = 'Test_user'
        email = '@3.ru'
        count = 2352

        payload = {
            'halt': 0,
        }
        result = []

        try:        
            for _ in range(50):
                payload['cmd']={}

                for _ in range(50):
                    payload['cmd']['add_user'+str(count)] = f'user.add?NAME={name+str(count)}&EMAIL={str(count)+email}&UF_DEPARTMENT=11&UF_PHONE_INNER={count}'
                    count += 1
                result.extend(b.call_batch(payload))
                del payload['cmd']
        finally:
            # вот тут нужно кошерно завершиться, удалив всех пользователей
```

И тут я понимаю, что в REST API нет метода, чтобы удалить пользователя: https://dev.1c-bitrix.ru/rest_help/users/index.php.

При этом на бесплатном аккаунте (который я использую для прогона тестов, а вы, полагаю, использовали его, когда столкнулись с проблемой выше) есть ограничение в 1000 сущностей каждого типа. То есть, прогнав один раз ваш код, мы упремся в ограничения тестового аккаунта и будем рисковать его блокировкой.

В связи с чем вопросы:
1. Вам так много пользователей нужно добавлять в связи с производственной необходимостью или вы тестируете API? Если тестируете, то можем ли тестировать на других типах сущностей, где есть удаление?
2. Возможно ли, что вы в своих тестах уперлись в какое-то ограничение Битрикса, связанное с количеством созданных пользователей?
3. Если у вас платный аккаунт для тестирования, можете ли вы его передать мне в личке, чтобы я на вашем аккаунте погонял тесты?

И предложение к вам: как я вижу, создание пользователя - операция, сильно нагружающая сервер Битрикса. Возможно, вам стоит обрамить ваши вызовы `user.add` контекстным менеджером `fast_bitrix24.slow()`, и вас все получится. См. https://github.com/leshchenko1979/fast_bitrix24#slowrequests_per_second-float--05

**Comment by ricotioloco** [comment]
Да, метода для удаления в Битрикс нет, как в общем и такого понятия в принципе) Там есть только увольнение. Пользователя на портале нет, но электронка его остается и никак оттуда ее не выковырять, потому что как битриксовцы утверждают это нужно для того, чтобы не удалились, то ли сообщения, где он мог писать, то ли посты, в общем чтобы логика не нарушилась. 
Аккаунт у меня да, бесплатный. Это мой тестовый портал, я на нем провожу тесты телефонии, т.к. я больше не по Битрикс, а по Астериск. Ну ограничение в 1000 пользователей я уже превысил, пока вроде не заблокировали, но возможно заблокировали использование batch, кто их знает. 
История такая, я работаю в фирме-интеграторе Битрикс) Я занимаюсь интеграцией астериск с битрикс (в техподдержке работаю). Возникла проблема, что в модуле интеграции  отображаются не все пользователи Битрикс (чтобы например назначать пользователя по-умолчанию). Т.е. то ли в модуле не отрабатывает batch, то ли проблема в чем-то другом. Т.к. программист занят, то решил сам заняться добавлением пользователей и проверкой, задача то казалась не сложной. Использовал requests для запросов. С не-batch запросами все нормально, но batch не пошел. Скорее всего я просто неправильно строил массивы при передаче в batch (от Битрикс возвращался пустой result).
Оборачивание в with slow(1) не изменило ситуацию. 
Буду дальше добавлять обычными запросами, еще один день и думаю получу свои 5000 пользователей) Параллельно напишу в ТП Битрикс, спрошу у них насчет ограничений бесплатной версии битрикса

**Comment by leshchenko1979** [comment]
> но возможно заблокировали использование batch, кто их знает.

По моему опыту, блокируют весь аккаунт.

> Буду дальше добавлять обычными запросами

OK. Батчи с лидами на тестах работают нормально. Я думаю, тут есть какая-то особенность именно по пользователям.

**Comment by ricotioloco** [comment]
В Битрикс любят выкатить фичу и не задокументировать. Хотя по пользователям ограничения в бесплатной версии нет. Ну да хрен с ней, надеюсь больше не придется этим заниматься)
![2020-11-25_15-22](https://user-images.githubusercontent.com/71933392/100227370-1c06a580-2f32-11eb-9bf2-bcee14687845.png)

**Comment by leshchenko1979** [comment]
Но вы все-таки попробуйте вот это, плз: https://github.com/leshchenko1979/fast_bitrix24/issues/85#issuecomment-732149535

**Comment by leshchenko1979** [comment]
На всякий пожарный запустил у себя тест. Предельно сохранил ваш код, но переключился на лиды:

```python
    def test_batch_issue_85(self, get_test):

        b = get_test

        name = 'Test_user'
        email = '@3.ru'
        count = 2352

        payload = {
            'halt': 0,
        }
        result = []

        try:
            for _ in range(10):
                payload['cmd']={}

                for _ in range(50):
                    payload['cmd']['add_user'+str(count)] = f'crm.lead.add?NAME={name+str(count)}&EMAIL={str(count)+email}&UF_DEPARTMENT=11&UF_PHONE_INNER={count}'
                    count += 1

                r = b.call_batch(payload)
                result.extend(r.values())
                del payload['cmd']
        finally:
            assert len(result) == 500
            assert len(result) == len(set(result)) # все ID уникальные
            b.call('crm.lead.delete', [{'ID': r} for r in result])
```

Работает нормально. Какая-то загвоздка именно с пользователями.
